# Generated by Django 6.0.4 on 2026-06-26 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Alert title', max_length=200)),
                ('description', models.TextField(help_text='Detailed alert description')),
                ('danger_type', models.CharField(help_text='Type of danger', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', help_text='Alert priority level', max_length=10)),
                ('severity', models.IntegerField(help_text='Severity score (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Alert latitude', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Alert longitude', max_digits=10)),
                ('address', models.CharField(blank=True, help_text='Human-readable address', max_length=255)),
                ('alert_radius_km', models.FloatField(default=1.0, help_text='Radius in kilometers for alert broadcasting')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='ACTIVE', help_text='Current alert status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('citizens_notified', models.IntegerField(default=0, help_text='Number of citizens who received this alert')),
                ('citizens_confirmed', models.IntegerField(default=0, help_text='Number of citizens who confirmed receiving')),
                ('is_active', models.BooleanField(default=True, help_text='Is this alert still active?')),
                ('assigned_team', models.ForeignKey(blank=True, help_text='Intervention team assigned to this alert', limit_choices_to={'role': 'INTERVENTION_TEAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Authority who created this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('report', models.OneToOneField(help_text='The report that triggered this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='reports.report')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Authority who resolved this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATED', 'Alert Created'), ('STATUS_CHANGE', 'Status Changed'), ('TEAM_ASSIGNED', 'Team Assigned'), ('NOTIFICATION_SENT', 'Notification Sent'), ('RESOLVED', 'Alert Resolved'), ('CLOSED', 'Alert Closed')], help_text='Type of action', max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(help_text='The alert this log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='alerts.alert')),
                ('performed_by', models.ForeignKey(help_text='Who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='alerts_status_0e4dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority'], name='alerts_priorit_9aa898_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['danger_type'], name='alerts_danger__a4f0fd_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['latitude', 'longitude'], name='alerts_latitud_e73077_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='alerts_created_6327ec_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active'], name='alerts_is_acti_449676_idx'),
        ),
    ]
