# Generated by Django 6.0.4 on 2026-06-26 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(help_text="Token FCM de l'appareil", max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', help_text="Type d'appareil", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text="L'appareil est-il actif ?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text="L'utilisateur propriétaire de l'appareil", on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fcm_devices',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'fcm_token')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ALERT', "Alerte d'urgence"), ('INTERVENTION', 'Mise à jour intervention'), ('REPORT_VERIFIED', 'Rapport vérifié'), ('POINTS_AWARDED', 'Points gagnés'), ('POINTS_REDEEMED', 'Points échangés'), ('STATUS_UPDATE', 'Mise à jour statut'), ('RESOLVED', 'Résolu'), ('SYSTEM', 'Notification système')], help_text='Type de notification', max_length=20)),
                ('title', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Message de la notification')),
                ('channel', models.CharField(choices=[('PUSH', 'Push Notification'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('IN_APP', 'In-App')], default='IN_APP', help_text="Canal d'envoi de la notification", max_length=10)),
                ('data', models.JSONField(default=dict, help_text='Données supplémentaires pour le frontend')),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image associée à la notification")),
                ('is_read', models.BooleanField(default=False, help_text='La notification a-t-elle été lue ?')),
                ('is_sent', models.BooleanField(default=False, help_text='La notification a-t-elle été envoyée ?')),
                ('read_at', models.DateTimeField(blank=True, help_text='Date de lecture de la notification', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text="Date d'envoi de la notification", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(blank=True, help_text="L'alerte associée à cette notification", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='alerts.alert')),
                ('intervention', models.ForeignKey(blank=True, help_text="L'intervention associée à cette notification", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='interventions.intervention')),
                ('recipient', models.ForeignKey(help_text="L'utilisateur qui reçoit la notification", on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='notificatio_recipie_1dd18d_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'), models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx')],
            },
        ),
    ]
