# Generated by Django 6.0.4 on 2026-06-26 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'intervention", max_length=200)),
                ('description', models.TextField(help_text="Description détaillée de l'intervention")),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assignée'), ('EN_ROUTE', 'En route'), ('ON_SITE', 'Sur place'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='ASSIGNED', help_text="Statut actuel de l'intervention", max_length=20)),
                ('latitude', models.DecimalField(decimal_places=7, help_text="Latitude du lieu d'intervention", max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text="Longitude du lieu d'intervention", max_digits=10)),
                ('address', models.CharField(blank=True, help_text="Adresse du lieu d'intervention", max_length=255)),
                ('estimated_arrival_minutes', models.IntegerField(blank=True, help_text="Temps estimé d'arrivée en minutes", null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, help_text="Heure réelle d'arrivée sur place", null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text="Heure de début de l'intervention", null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text="Heure de fin de l'intervention", null=True)),
                ('team_notes', models.TextField(blank=True, help_text="Notes prises par l'équipe pendant l'intervention")),
                ('outcome', models.TextField(blank=True, help_text="Résultat de l'intervention")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.OneToOneField(help_text="L'alerte à laquelle cette intervention est associée", on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='alerts.alert')),
                ('created_by', models.ForeignKey(help_text="L'autorité qui a créé cette intervention", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interventions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(help_text="L'équipe d'intervention assignée", limit_choices_to={'role': 'INTERVENTION_TEAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('ASSIGNED', 'Assignée'), ('EN_ROUTE', 'En route'), ('ON_SITE', 'Sur place'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], help_text='Statut avant la mise à jour', max_length=20)),
                ('new_status', models.CharField(choices=[('ASSIGNED', 'Assignée'), ('EN_ROUTE', 'En route'), ('ON_SITE', 'Sur place'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], help_text='Statut après la mise à jour', max_length=20)),
                ('message', models.TextField(help_text='Description de la mise à jour')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intervention', models.ForeignKey(help_text="L'intervention concernée", on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='interventions.intervention')),
                ('updated_by', models.ForeignKey(help_text='La personne qui a fait cette mise à jour', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intervention_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['status'], name='interventio_status_579a12_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['team'], name='interventio_team_id_c49121_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['alert'], name='interventio_alert_i_9f5ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['latitude', 'longitude'], name='interventio_latitud_f87681_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['-created_at'], name='interventio_created_ea258b_idx'),
        ),
    ]
