# Generated by Django 5.2.15 on 2026-06-17 08:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short title of the danger (e.g., 'Fire at Mokolo Market')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what was observed')),
                ('danger_type', models.CharField(blank=True, choices=[('FIRE', 'Fire'), ('FLOOD', 'Flood'), ('WASTE', 'Illegal Waste'), ('DEFORESTATION', 'Deforestation'), ('POLLUTION', 'Pollution'), ('ROAD_HAZARD', 'Road Hazard'), ('OTHER', 'Other')], help_text='AI-detected or manually selected danger type', max_length=20, null=True)),
                ('severity', models.IntegerField(blank=True, help_text='Severity level (1-10, where 10 is most severe)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('confidence_score', models.IntegerField(blank=True, help_text='AI confidence score (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('latitude', models.DecimalField(decimal_places=7, help_text='GPS Latitude of the danger location', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='GPS Longitude of the danger location', max_digits=10)),
                ('address', models.CharField(blank=True, help_text='Human-readable address of the location', max_length=255)),
                ('gps_accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('status', models.CharField(choices=[('PENDING_AI', 'Pending AI Analysis'), ('CROWD_VERIFY', 'Under Crowd Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged for Review'), ('ALERT_CREATED', 'Alert Created'), ('RESOLVED', 'Resolved')], default='PENDING_AI', help_text='Current status of the report', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the report was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the report was last updated')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the report was verified', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the incident was resolved', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Has an authority verified this report?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this report still active/visible?')),
                ('crowd_confirmations', models.IntegerField(default=0, help_text='Number of nearby citizens who confirmed this report')),
                ('crowd_denials', models.IntegerField(default=0, help_text='Number of nearby citizens who denied this report')),
                ('crowd_verification_completed', models.BooleanField(default=False, help_text='Has crowd verification finished?')),
                ('points_awarded', models.IntegerField(default=0, help_text='Points awarded to the reporter')),
                ('money_earned_cfa', models.DecimalField(decimal_places=2, default=0.0, help_text='Money earned in CFA for this report', max_digits=10)),
                ('device_model', models.CharField(blank=True, help_text='Mobile device model used to submit', max_length=100)),
                ('app_version', models.CharField(blank=True, help_text='App version used to submit', max_length=20)),
                ('reporter', models.ForeignKey(help_text='The citizen who submitted this report', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Authority who verified this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('CONFIRM', 'I confirm this danger exists'), ('DENY', "I don't see this danger"), ('UNSURE', "I'm not sure")], help_text="Citizen's response (confirm, deny, or unsure)", max_length=10)),
                ('comment', models.TextField(blank=True, help_text='Optional comment from the citizen')),
                ('responded_at', models.DateTimeField(auto_now_add=True, help_text='When the citizen responded')),
                ('is_verified', models.BooleanField(default=False, help_text='Is this response verified as genuine?')),
                ('citizen', models.ForeignKey(help_text='The citizen responding to the verification request', on_delete=django.db.models.deletion.CASCADE, related_name='verification_responses', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='The report being verified by the crowd', on_delete=django.db.models.deletion.CASCADE, related_name='crowd_verifications', to='reports.report')),
            ],
            options={
                'db_table': 'crowd_verifications',
            },
        ),
        migrations.CreateModel(
            name='ReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded evidence file (image, video, or audio)', upload_to='reports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov', 'mp3', 'wav'])])),
                ('evidence_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], help_text='Type of evidence (image, video, or audio)', max_length=10)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('original_filename', models.CharField(help_text="Original filename from user's device", max_length=255)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Display order of evidence')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When this evidence was uploaded')),
                ('report', models.ForeignKey(help_text='The report this evidence belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='reports.report')),
            ],
            options={
                'db_table': 'report_evidence',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter'], name='reports_reporte_5cbb43_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_status_e83c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['danger_type'], name='reports_danger__6ac6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['latitude', 'longitude'], name='reports_latitud_37cc41_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_created_c5f642_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['-created_at'], name='reports_created_49202c_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['is_verified'], name='reports_is_veri_42ef73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crowdverification',
            unique_together={('report', 'citizen')},
        ),
    ]
