# Generated by Django 5.2.15 on 2026-06-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid_danger', models.BooleanField(default=False, help_text='Is this a valid environmental danger?')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why this was rejected (if not a danger)')),
            ],
        ),
    ]
