# Generated by Django 6.0.4 on 2026-06-26 17:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danger_type', models.CharField(blank=True, choices=[('FIRE', 'Feu'), ('FLOOD', 'Inondation'), ('WASTE', 'Déchet illégal'), ('DEFORESTATION', 'Déforestation'), ('POLLUTION', 'Pollution'), ('ROAD_HAZARD', 'Danger routier'), ('OTHER', 'Autre')], max_length=20, null=True)),
                ('severity_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('severity_level', models.CharField(blank=True, choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], max_length=10, null=True)),
                ('confidence_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommended_action', models.CharField(blank=True, choices=[('IMMEDIATE_EVACUATION', 'Évacuation immédiate'), ('CALL_FIRE_DEPARTMENT', 'Appeler les pompiers'), ('CALL_POLICE', 'Appeler la police'), ('CALL_AMBULANCE', 'Appeler une ambulance'), ('AVOID_AREA', 'Éviter la zone'), ('MONITOR_SITUATION', 'Surveiller la situation'), ('CONTACT_AUTHORITIES', 'Contacter les autorités'), ('NO_ACTION', 'Aucune action requise')], max_length=30, null=True)),
                ('advice', models.TextField(blank=True)),
                ('safety_tips', models.TextField(blank=True)),
                ('emergency_contacts', models.TextField(blank=True)),
                ('is_valid_danger', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_successful', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='reports.report')),
            ],
            options={
                'db_table': 'ai_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
